windows.yml aktualisieren

diff --git a/.github/workflows/windows.yml b/.github/workflows/windows.yml
--- a/.github/workflows/windows.yml
+++ b/.github/workflows/windows.yml
@@ -82,33 +82,33 @@ jobs:
           arch: ${{ matrix.os.architecture }}
 
       - name: Download/Install Inno Setup
-            run: |
-              echo "Checking pre-installation..."
-              
-              set "ISCC_PATH=%programfiles(x86)%\Inno Setup 6\ISCC.exe"
-              
-              if exist "%ISCC_PATH%" (
-                echo ::warning::Inno Setup is already installed
-                exit /b 0
-              )
-              
-              echo "Downloading Inno Setup..."
-      
-              set "_url_=https://jrsoftware.org/download.php/is.exe?site=1"
-              set "_file_=innosetup.exe"
-      
-              curl -L -o "%tmp%\%_file_%" "%_url_%"
-              
-              echo "Installing Inno Setup..."
-              "%tmp%\%_file_%" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
-              
-              if not exist "%ISCC_PATH%" (
-                echo "::error::Inno Setup installation failed"
-                exit 1
-              )
-              
-              echo ::warning::Inno Setup installed successfully!
-            shell: cmd
+        run: |
+          echo "Checking pre-installation..."
+          
+          set "ISCC_PATH=%programfiles(x86)%\Inno Setup 6\ISCC.exe"
+          
+          if exist "%ISCC_PATH%" (
+            echo ::warning::Inno Setup is already installed
+            exit /b 0
+          )
+          
+          echo "Downloading Inno Setup..."
+  
+          set "_url_=https://jrsoftware.org/download.php/is.exe?site=1"
+          set "_file_=innosetup.exe"
+  
+          curl -L -o "%tmp%\%_file_%" "%_url_%"
+          
+          echo "Installing Inno Setup..."
+          "%tmp%\%_file_%" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
+          
+          if not exist "%ISCC_PATH%" (
+            echo "::error::Inno Setup installation failed"
+            exit 1
+          )
+          
+          echo ::warning::Inno Setup installed successfully!
+        shell: cmd
           
       - name: 💾 Download Pre-Build Dependencies
         id: dependencies
